name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: poc
        run:  |
          export CI_BRANCH=${BRANCH_NAME_OR_REF#refs/heads/}
          export CI_PULL_REQUEST=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        env:
          CI_NAME: github
          BRANCH_NAME_OR_REF: ${{ github.head_ref || github.ref }}
          CI_BUILD_URL: https://github.com/${{ github.repository }}/commit/${{ github.event.after }}/checks
          COVERALLS_SECRET: HONKHONKHONK
